# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('created', models.DateTimeField(verbose_name='auto_now_add=True')),
                ('weight', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.URLField()),
            ],
        ),
    ]
