# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='fish',
            name='created',
        ),
    ]
