# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_auto_20160423_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={},
        ),
    ]
